import { defineDynamic, defineTool, type ToolContext } from "eve/tools";

import { readPreparedWorkspace } from "../../src/git-workspace.js";
import { createGitHubDraftPullRequestPublisher } from "../../src/github-publisher.js";
import { publishSelfModification } from "../../src/publisher.js";
import {
  resolveSelfModificationConfig,
  type ResolvedSelfModificationPullRequests,
} from "../../src/config.js";
import { resolveSelfModificationMode } from "../../src/mode.js";
import {
  assertSelfModificationPullRequestsAvailable,
  resolvePersonalAccessToken,
} from "../../src/pull-requests.js";
import selfModification from "../extension.js";

const inputSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    summary: {
      type: "string",
      minLength: 1,
      maxLength: 10_000,
      description: "Concise description of the proposed source change.",
    },
    title: {
      type: "string",
      minLength: 1,
      maxLength: 256,
      description: "Concise draft pull request title.",
    },
  },
  required: ["summary", "title"],
} as const;

const outputSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    base: { type: "string" },
    branch: { type: "string" },
    changedPaths: { type: "array", items: { type: "string" } },
    commitSha: { type: "string" },
    deployedSha: { type: "string" },
    draft: { type: "boolean" },
    pullRequestState: { type: "string", enum: ["closed", "open"] },
    pullRequestUrl: { type: "string" },
    targetBranch: { type: "string" },
  },
  required: [
    "base",
    "branch",
    "changedPaths",
    "commitSha",
    "deployedSha",
    "draft",
    "pullRequestState",
    "pullRequestUrl",
    "targetBranch",
  ],
} as const;

export function defineSelfModificationPublishTool(
  pullRequestsOverride?: ResolvedSelfModificationPullRequests,
) {
  const resolve = () => {
    const config = resolveSelfModificationConfig(selfModification.config);
    const pullRequests = pullRequestsOverride ?? config.pullRequests;
    return pullRequests !== undefined &&
      resolveSelfModificationMode({ ...config, pullRequests }) === "pull-requests"
      ? createSelfModificationPublishTool(pullRequests)
      : null;
  };

  return defineDynamic({
    events: {
      "session.started": resolve,
      "turn.started": resolve,
    },
  });
}

function createSelfModificationPublishTool(pullRequests: ResolvedSelfModificationPullRequests) {
  return defineTool({
    description:
      "Publish the complete proposed source change as a draft pull request for repository review. Call only after restating the changed scope.",
    inputSchema,
    outputSchema,
    async execute(input, ctx) {
      if (
        typeof input.summary !== "string" ||
        input.summary.length === 0 ||
        input.summary.length > 10_000 ||
        typeof input.title !== "string" ||
        input.title.length === 0 ||
        input.title.length > 256
      ) {
        throw new Error("Self-modification publish requires a valid title and summary.");
      }
      const source = assertSelfModificationPullRequestsAvailable({ pullRequests });
      const operationId = operationIdFromContext(ctx);
      const sandbox = await ctx.getSandbox();
      const workspace = await readPreparedWorkspace(sandbox, source.revision, source.rootDirectory);
      const body = [
        input.summary,
        "",
        "---",
        "",
        "Generated by eve self-modification from a deployed conversation.",
        `- Deployed revision: \`${source.revision}\``,
        `- Operation: \`${operationId}\``,
      ].join("\n");

      const published = await publishSelfModification({
        publisher: createGitHubDraftPullRequestPublisher({
          personalAccessToken: resolvePersonalAccessToken,
          repository: pullRequests.repository,
        }),
        request: {
          deployedSha: source.revision,
          description: body,
          operationId,
          sandbox,
          title: input.title,
          workspace,
        },
      });
      return published;
    },
  });
}

export function operationIdFromContext(ctx: {
  readonly session: { readonly parent?: ToolContext["session"]["parent"] };
}): string {
  const parent = ctx.session.parent;
  if (parent === undefined) {
    throw new Error("Deployed self-modification publication requires a delegated child session.");
  }
  return `${parent.rootSessionId}:${parent.turn.id}:${parent.callId}`;
}

export const readWorkspaceContext = readPreparedWorkspace;

export default defineSelfModificationPublishTool();
