import { getVercelOidcToken } from "#compiled/@vercel/oidc/index.js";

import { VERCEL_TRUSTED_OIDC_IDP_TOKEN_HEADER, type HeadersValue } from "#client/types.js";
import { isEveDevEnvironment } from "#internal/application/dev-environment.js";
import type { OutboundAuthFn } from "#public/agents/auth.js";
import type { RemoteAgentUrl } from "#public/definitions/remote-agent.js";

/** Catalog metadata for one selected workspace member. */
export interface WorkspaceSubagentMember {
  readonly description?: string;
  readonly name: string;
  readonly path: string;
}

/** Runtime connection details for one selected workspace member. */
export interface WorkspaceSubagentTarget {
  readonly auth?: OutboundAuthFn;
  readonly headers?: HeadersValue;
  readonly url: RemoteAgentUrl;
}

/** Resolves a selected workspace member's remote target at runtime. */
export type WorkspaceSubagentTargetResolver = (
  member: WorkspaceSubagentMember,
) => WorkspaceSubagentTarget | Promise<WorkspaceSubagentTarget>;

export interface WorkspaceSubagentsDefinition {
  readonly exclude?: readonly string[];
  readonly forwardPrincipal?: boolean;
  readonly include?: readonly string[];
  readonly kind: "workspace-subagents";
  readonly resolveTarget: WorkspaceSubagentTargetResolver;
}

/** Selects workspace members and exposes them as remote subagents. */
export function defineWorkspaceSubagents(
  definition: Omit<WorkspaceSubagentsDefinition, "kind">,
): WorkspaceSubagentsDefinition {
  return { ...definition, kind: "workspace-subagents" };
}

/** Targets members through the routes generated by an eve Vercel workspace deployment. */
export function vercelWorkspaceTarget(): WorkspaceSubagentTargetResolver {
  return (member) => ({
    auth: async () => {
      if (isEveDevEnvironment()) {
        return { headers: {} as Readonly<Record<string, string>> };
      }
      const token = await getVercelOidcToken({});
      return {
        headers: {
          authorization: `Bearer ${token}`,
          [VERCEL_TRUSTED_OIDC_IDP_TOKEN_HEADER]: token,
        },
      };
    },
    url: () => {
      if (isEveDevEnvironment()) return "http://127.0.0.1:1";
      const host =
        process.env.VERCEL_ENV === "production"
          ? process.env.VERCEL_PROJECT_PRODUCTION_URL
          : process.env.VERCEL_URL;
      if (!host) {
        throw new Error(
          "vercelWorkspaceTarget() requires VERCEL_URL, or VERCEL_PROJECT_PRODUCTION_URL in production.",
        );
      }
      return `https://${host}/eve/agents/${member.name}`;
    },
  });
}
