import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import type { TemplateFile } from "../lib/templates/compose";
import { templateManifest } from "../lib/templates/manifest";
import {
  commitUrl,
  contentsUrl,
  decodeContentsResponse,
  sortTemplateFiles,
  type GitHubContentsResponse,
} from "../lib/templates/sync-core";

const token = process.env.GITHUB_TOKEN;
const headers: Record<string, string> = {
  Accept: "application/vnd.github+json",
  "X-GitHub-Api-Version": "2022-11-28",
};
if (token) headers.Authorization = `Bearer ${token}`;

const githubJson = async <T>(url: string, notFoundMessage: string): Promise<T> => {
  const response = await fetch(url, { headers });
  if (response.status === 404) {
    throw new Error(notFoundMessage);
  }
  if (response.status === 403 || response.status === 429) {
    throw new Error(
      `GitHub API rate limit or access error (${response.status}) for ${url}` +
        (token ? "" : " — set GITHUB_TOKEN to authenticate"),
    );
  }
  if (!response.ok) {
    throw new Error(`GitHub API request failed (${response.status}) for ${url}`);
  }
  return (await response.json()) as T;
};

console.log(`Syncing templates from GitHub (${token ? "authenticated" : "unauthenticated"})`);

const templates: Record<string, { readme: string; sourceRevision: string; files: TemplateFile[] }> =
  {};

for (const entry of templateManifest) {
  const { github } = entry;
  const commit = await githubJson<{ sha: string }>(
    commitUrl(github),
    `Ref "${github.ref}" not found in ${github.owner}/${github.repo} (template "${entry.slug}")`,
  );

  const files: TemplateFile[] = [];
  for (const relativePath of entry.files) {
    const contents = await githubJson<GitHubContentsResponse>(
      contentsUrl(github, commit.sha, relativePath),
      `Curation drift: "${relativePath}" is listed in the manifest for template "${entry.slug}" ` +
        `but does not exist in ${github.owner}/${github.repo}@${commit.sha}`,
    );
    files.push(decodeContentsResponse(relativePath, contents));
  }

  const readmeResponse = await githubJson<GitHubContentsResponse>(
    contentsUrl(github, commit.sha, "README.md"),
    `README.md not found for template "${entry.slug}" in ` +
      `${github.owner}/${github.repo}@${commit.sha}`,
  );
  const readme = decodeContentsResponse("README.md", readmeResponse).contents;

  templates[entry.slug] = {
    files: sortTemplateFiles(files),
    readme,
    sourceRevision: commit.sha,
  };
  console.log(`${entry.slug} ${github.ref} → ${commit.sha.slice(0, 7)} (${files.length} files)`);
}

const output = {
  $comment:
    "Generated by scripts/sync-templates.ts. Do not edit. Run: pnpm --filter eve-docs templates:sync",
  templates,
};

const outputPath = join(import.meta.dirname, "../lib/templates/generated/templates.json");
await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, `${JSON.stringify(output, null, 2)}\n`);
console.log(`Wrote ${outputPath}`);
