#!/usr/bin/env node

import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { realpathSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

import { SELF_MODIFICATION_CONFIG_PATH } from "./git-workspace.js";

import {
  createRegistrySetupClient,
  WizardCancelledError,
  type RegistrySetupClient,
} from "eve/setup";

const runFile = promisify(execFile);

const TOKEN_ENV = "EVE_SELF_MODIFICATION_GITHUB_TOKEN";
const DEVELOPMENT_CONFIG = `import { defineSelfModificationConfig } from "@eve/self-modification/config";

export default defineSelfModificationConfig({});
`;
const GENERATED_HEADER_PREFIX = "// Generated by @eve/self-modification setup v5; body-sha256:";

export interface ReviewSetupValues {
  readonly branch: string;
  readonly repository: string;
}

export type DeploymentSetupTarget = "manual" | "vercel";

export type SelfModificationConfigState =
  | { readonly kind: "development" }
  | { readonly kind: "review"; readonly values: ReviewSetupValues }
  | { readonly kind: "diverged" };

export interface DetectedGitRepository {
  readonly owner?: string;
  readonly baseBranch?: string;
  readonly remoteKind: "github" | "missing" | "other";
  readonly repo?: string;
  readonly rootDirectory?: string;
}

export interface SelfModificationSetupOperations {
  detectGitRepository(): Promise<DetectedGitRepository>;
  readConfig(): Promise<string | undefined>;
  writeConfig(source: string): Promise<void>;
}

export function parseGitHubRemote(remote: string): { owner: string; repo: string } | undefined {
  const match = remote
    .trim()
    .match(
      /^(?:https?:\/\/github\.com\/|git@github\.com:|ssh:\/\/git@github\.com\/)([^/]+)\/([^/]+?)(?:\.git)?$/u,
    );
  if (match === null || match[1] === undefined || match[2] === undefined) return undefined;
  return { owner: match[1], repo: match[2] };
}

export function inspectSelfModificationConfig(
  source: string | undefined,
): SelfModificationConfigState {
  if (source === DEVELOPMENT_CONFIG) return { kind: "development" };
  if (source === undefined) return { kind: "diverged" };
  const newline = source.indexOf("\n");
  if (newline === -1) return { kind: "diverged" };
  const header = source.slice(0, newline);
  const body = source.slice(newline + 1);
  if (
    !header.startsWith(GENERATED_HEADER_PREFIX) ||
    header.slice(GENERATED_HEADER_PREFIX.length) !== bodyDigest(body)
  ) {
    return { kind: "diverged" };
  }
  const match = body.match(/const setup = (\{[\s\S]*\}) as const;\n/u);
  if (match?.[1] === undefined) return { kind: "diverged" };
  try {
    const values: unknown = JSON.parse(match[1]);
    return isReviewSetupValues(values) ? { kind: "review", values } : { kind: "diverged" };
  } catch {
    return { kind: "diverged" };
  }
}

export function renderSelfModificationConfig(values: ReviewSetupValues): string {
  const body = `import { defineSelfModificationConfig } from "@eve/self-modification/config";

const setup = ${JSON.stringify(values, null, 2)} as const;

export default defineSelfModificationConfig({
  source: {
    git: {
      repository: setup.repository,
    },
  },
  change: {
    behavior: "review",
    branch: setup.branch,
  },
});
`;
  return `${GENERATED_HEADER_PREFIX}${bodyDigest(body)}\n${body}`;
}

function bodyDigest(body: string): string {
  return createHash("sha256").update(body).digest("hex");
}

export async function runSelfModificationSetup(
  client: RegistrySetupClient,
  operations: SelfModificationSetupOperations,
  options: { readonly yes?: boolean } = {},
): Promise<void> {
  const { prompter } = client;
  prompter.intro("Set up self-modification", "Local source editing is enabled by default.");

  if (options.yes === true) {
    prompter.log.info(
      "Keeping self-modification local-only. Draft pull requests require interactive setup.",
    );
    client.complete({ facts: [{ label: "Self-modification", value: "local editing" }] });
    return;
  }

  const current = inspectSelfModificationConfig(await operations.readConfig());
  if (current.kind === "review") {
    prompter.log.success(
      `Draft pull request configuration is present for ${current.values.repository}.`,
    );
    prompter.log.info(
      "The deployed subagent appears only when the build captures matching source metadata and the deployment provides a GitHub credential. Preparing a proposal also requires a process-capable sandbox.",
    );
    client.complete({
      facts: [{ label: "Self-modification", value: "draft pull request configuration present" }],
    });
    return;
  }

  const deploymentTarget = await prompter.select({
    message: "Configure draft pull requests for which environment?",
    initialValue: "local",
    options: [
      { value: "local", label: "Local editing only", hint: "No deployment setup required" },
      {
        value: "vercel",
        label: "Git-connected Vercel deployment",
        hint: "GitHub source metadata and Vercel Sandbox are provided by the deployment",
      },
      {
        value: "manual",
        label: "CI or self-hosted deployment",
        hint: "Requires manual build metadata and a process-capable sandbox",
      },
    ],
  });
  if (deploymentTarget === "local") {
    client.complete({ facts: [{ label: "Self-modification", value: "local editing" }] });
    return;
  }

  const detected = await operations.detectGitRepository();
  if (detected.remoteKind === "other") {
    prompter.note(
      "The configured Git remote is not GitHub. Self-modification currently publishes only to GitHub.",
      "GitHub repository required",
      { tone: "warning" },
    );
  }
  const owner = await prompter.text({
    message: "GitHub repository owner",
    defaultValue: detected.owner,
    validate: repositoryPartError,
  });
  const repo = await prompter.text({
    message: "GitHub repository name",
    defaultValue: detected.repo,
    validate: repositoryPartError,
  });
  const baseBranch = await prompter.text({
    message: "Pull request base branch",
    defaultValue: detected.baseBranch ?? "main",
    validate: gitRefError,
  });
  const values: ReviewSetupValues = {
    branch: baseBranch,
    repository: `github.com/${owner}/${repo}`,
  };
  const source = renderSelfModificationConfig(values);

  prompter.note(source, `Generated ${SELF_MODIFICATION_CONFIG_PATH}`);
  prompter.note(
    deploymentPrerequisites(deploymentTarget, values, detected.rootDirectory),
    deploymentTarget === "vercel"
      ? "Vercel deployment requirements"
      : "Manual deployment requirements",
  );
  prompter.note(
    [
      `Restrict ${TOKEN_ENV} to ${values.repository} with Contents: read and write, Pull requests: read and write, and Metadata: read.`,
      "The token is resolved only during checkout and draft pull request publication and is never written to source.",
      "Every session accepted by a supported deployment can request a proposal. Protect public routes and channels before enabling this flow.",
      "Publication can create only a namespaced branch and draft pull request; repository review and merge remain separate boundaries.",
    ].join("\n"),
    "Pull request boundaries",
  );
  const confirm = await prompter.select({
    message: "Write this self-modification configuration?",
    initialValue: "no",
    options: [
      { value: "no", label: "No, keep local editing only" },
      { value: "yes", label: "Yes, write configuration" },
    ],
  });
  if (confirm === "no") {
    client.complete({ facts: [{ label: "Self-modification", value: "local editing" }] });
    return;
  }
  if (current.kind === "diverged") {
    prompter.note(
      `The existing ${SELF_MODIFICATION_CONFIG_PATH} is authored or has diverged. It was not overwritten. Apply the generated configuration manually.`,
      "Manual update required",
      { tone: "warning" },
    );
    client.complete({
      facts: [{ label: "Self-modification", value: "manual configuration update required" }],
    });
    return;
  }

  await operations.writeConfig(source);
  prompter.log.success(`Updated ${SELF_MODIFICATION_CONFIG_PATH}.`);
  prompter.outro(
    deploymentTarget === "vercel"
      ? `Add ${TOKEN_ENV}, then deploy through the Git-connected GitHub project.`
      : "Configure the listed build metadata, credential, and sandbox before deploying.",
  );
  client.complete({
    deploymentRequired: true,
    facts: [
      { label: "Self-modification", value: "draft pull request configuration written" },
      { label: "Repository", value: values.repository },
      {
        label: "Deployment",
        value: deploymentTarget === "vercel" ? "Git-connected Vercel" : "manual prerequisites",
      },
      { label: "Credential", value: TOKEN_ENV },
    ],
  });
}

export function defaultSelfModificationSetupOperations(
  appRoot: string,
): SelfModificationSetupOperations {
  const configPath = join(appRoot, SELF_MODIFICATION_CONFIG_PATH);
  return {
    async detectGitRepository() {
      const remote = await gitOutput(appRoot, ["config", "--get", "remote.origin.url"]);
      const repository = remote === undefined ? undefined : parseGitHubRemote(remote);
      const remoteKind =
        remote === undefined ? "missing" : repository === undefined ? "other" : "github";
      const remoteHead = await gitOutput(appRoot, [
        "symbolic-ref",
        "--quiet",
        "--short",
        "refs/remotes/origin/HEAD",
      ]);
      const repositoryRoot = await gitOutput(appRoot, ["rev-parse", "--show-toplevel"]);
      return {
        ...repository,
        baseBranch: remoteHead?.replace(/^origin\//u, ""),
        remoteKind,
        rootDirectory:
          repositoryRoot === undefined ? undefined : relative(repositoryRoot, appRoot) || ".",
      };
    },
    async readConfig() {
      try {
        return await readFile(configPath, "utf8");
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
        throw error;
      }
    },
    writeConfig: (source) => writeFile(configPath, source, "utf8"),
  };
}

function deploymentPrerequisites(
  target: DeploymentSetupTarget,
  values: ReviewSetupValues,
  rootDirectory: string | undefined,
): string {
  if (target === "vercel") {
    return [
      "Deploy through a Git-connected Vercel project backed by this GitHub repository.",
      "The deployed subagent remains hidden when Vercel does not provide complete Git source metadata, including for a non-Git-connected CLI deployment.",
      `Store a fine-grained GitHub personal access token in ${TOKEN_ENV}.`,
      "Vercel Sandbox provides the required process-capable workspace.",
    ].join("\n");
  }
  return [
    "Set these values in the trusted CI environment that runs `eve build`:",
    `EVE_SOURCE_REPOSITORY=${values.repository}`,
    "EVE_SOURCE_REVISION=<trusted-ci-commit-sha>",
    `EVE_SOURCE_ROOT=${rootDirectory ?? "<repository-relative-app-root>"}`,
    `Store a fine-grained GitHub personal access token in ${TOKEN_ENV}.`,
    "Configure `sandbox.ts` with a process-capable Docker, microsandbox, or custom backend.",
    "The deployed subagent remains hidden when source metadata is incomplete or does not match the configured repository.",
  ].join("\n");
}

function isReviewSetupValues(value: unknown): value is ReviewSetupValues {
  if (typeof value !== "object" || value === null) return false;
  const candidate = value as Partial<ReviewSetupValues>;
  const repository = candidate.repository?.match(/^github\.com\/([^/]+)\/([^/]+)$/u);
  return (
    repository?.[1] !== undefined &&
    repositoryPartError(repository[1]) === undefined &&
    repository[2] !== undefined &&
    repositoryPartError(repository[2]) === undefined &&
    typeof candidate.branch === "string" &&
    gitRefError(candidate.branch) === undefined
  );
}

function repositoryPartError(value: string): string | undefined {
  return /^[A-Za-z0-9_.-]+$/u.test(value) ? undefined : "Enter a GitHub owner or repository name.";
}

function gitRefError(value: string): string | undefined {
  return /^[A-Za-z0-9][A-Za-z0-9._/-]*$/u.test(value) &&
    !value.endsWith(".") &&
    !value.endsWith("/") &&
    !value.includes("..") &&
    !value.includes("//") &&
    !value.includes("@{")
    ? undefined
    : "Enter a valid branch name.";
}

async function gitOutput(appRoot: string, args: string[]): Promise<string | undefined> {
  try {
    const result = await runFile("git", args, { cwd: appRoot });
    const value = result.stdout.trim();
    return value.length === 0 ? undefined : value;
  } catch {
    return undefined;
  }
}

async function main(): Promise<void> {
  const client = createRegistrySetupClient();
  if (client === undefined) {
    throw new Error(
      "@eve/self-modification setup must be run by `eve add experimental/self-modification`.",
    );
  }
  try {
    await runSelfModificationSetup(client, defaultSelfModificationSetupOperations(process.cwd()), {
      yes: process.argv.includes("--yes"),
    });
  } catch (error) {
    if (error instanceof WizardCancelledError || client.signal.aborted) client.cancel();
    else client.fail(error);
  }
}

if (
  process.argv[1] !== undefined &&
  realpathSync(fileURLToPath(import.meta.url)) === realpathSync(process.argv[1])
) {
  void main();
}
