packages:
  - "."

minimumReleaseAgeExclude:
  - "@ai-sdk/*"
  - "@vercel/connect"
  - ai
  - eve

allowBuilds:
  "@parcel/watcher": false
  better-sqlite3: true
  esbuild: true
  sharp: false
  vue-demi: false
