import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import type { CompileMetadata } from "#compiler/artifacts.js";
import type { CompileAgentResult } from "#compiler/compile-agent.js";
import { createCompiledModuleMapSource } from "#compiler/module-map.js";
import { getWorldImport } from "@workflow/utils";
import { stringifyEsmImportSpecifier } from "#internal/application/import-specifier.js";
import {
  resolvePackageCompiledFilePath,
  resolvePackageSourceFilePath,
} from "#internal/application/package.js";
import type { AgentWorkflowWorldDefinition } from "#shared/agent-definition.js";

/**
 * Paths to the generated compiled-artifacts files shared by Nitro and the
 * vendored workflow bundles for one application.
 */
export interface GeneratedCompiledArtifactsFiles {
  /**
   * Shared bundled-artifacts bootstrap installed by Nitro and vendored
   * workflow handlers.
   */
  bootstrapPath: string;
  /** Nitro plugin that installs the selected vendored Workflow world. */
  workflowWorldPluginPath: string;
  /**
   * Optional Nitro plugin that imports the authored instrumentation module
   * from the application when present.
   */
  instrumentationPluginPath?: string;
  /**
   * Absolute path to the authored instrumentation module when present.
   * Nitro uses this to preserve the module's side effects during bundling.
   */
  instrumentationSourcePath?: string;
}

/**
 * Writes the generated compiled-artifacts bootstrap module.
 *
 * The bootstrap self-installs bundled artifacts on import and exports a
 * default function so it can be used directly as a Nitro plugin — no
 * separate plugin wrapper file is needed.
 */
export async function writeCompiledArtifactsFiles(input: {
  compileResult: CompileAgentResult;
  outDir: string;
}): Promise<GeneratedCompiledArtifactsFiles> {
  const bootstrapPath = join(input.outDir, "compiled-artifacts-bootstrap.mjs");
  const instrumentationPluginPath = join(input.outDir, "compiled-artifacts-instrumentation.mjs");
  const workflowWorldPluginPath = join(input.outDir, "compiled-artifacts-workflow-world.mjs");
  const instrumentationPath = resolveInstrumentationModule(input.compileResult.manifest.agentRoot);

  await mkdir(input.outDir, { recursive: true });
  await writeFile(
    bootstrapPath,
    await createCompiledArtifactsBootstrapSource({
      compileResult: input.compileResult,
      installModulePath: resolvePackageSourceFilePath("src/runtime/loaders/bundled-artifacts.ts"),
      moduleMapPath: bootstrapPath,
      metadata: input.compileResult.metadata,
    }),
  );
  await writeFile(
    workflowWorldPluginPath,
    createWorkflowWorldPluginSource(
      input.compileResult.manifest.config.experimental?.workflow?.world,
      bootstrapPath,
    ),
  );

  if (instrumentationPath !== undefined) {
    await writeFile(
      instrumentationPluginPath,
      createInstrumentationPluginSource({
        agentName: input.compileResult.manifest.config.name,
        instrumentationPath,
        registerConfigPath: resolvePackageSourceFilePath("src/harness/instrumentation-config.ts"),
      }),
    );
  }

  const generatedArtifacts: GeneratedCompiledArtifactsFiles = {
    bootstrapPath,
    workflowWorldPluginPath,
  };

  if (instrumentationPath !== undefined) {
    generatedArtifacts.instrumentationPluginPath = instrumentationPluginPath;
    generatedArtifacts.instrumentationSourcePath = instrumentationPath;
  }

  return generatedArtifacts;
}

const INSTRUMENTATION_EXTENSIONS = [".ts", ".mts", ".js", ".mjs"];

/**
 * Resolves the optional `agent/instrumentation` module from the agent root
 * directory. Returns the absolute path if found, `undefined` otherwise.
 */
function resolveInstrumentationModule(agentRoot: string): string | undefined {
  for (const ext of INSTRUMENTATION_EXTENSIONS) {
    const candidate = join(agentRoot, `instrumentation${ext}`);
    if (existsSync(candidate)) {
      return candidate;
    }
  }

  return undefined;
}

function stripCompiledModuleMapExports(source: string): string {
  return source
    .replace(/^export const moduleMap = /m, "const moduleMap = ")
    .replace(/\nexport default moduleMap;\n?$/, "\n");
}

export async function createCompiledArtifactsBootstrapSource(input: {
  compileResult: CompileAgentResult;
  installModulePath: string;
  metadata: CompileMetadata;
  moduleMapPath: string;
}): Promise<string> {
  const agentName = input.compileResult.manifest.config.name;
  const moduleMapSource = stripCompiledModuleMapExports(
    createCompiledModuleMapSource({
      importSpecifierStyle: "absolute",
      manifest: input.compileResult.manifest,
      moduleMapPath: input.moduleMapPath,
    }),
  ).trim();

  return [
    "// Generated by eve. Do not edit by hand.",
    `import { installBundledCompiledArtifacts } from ${stringifyEsmImportSpecifier(input.installModulePath)};`,
    `import { installEveWorkflowQueueNamespace } from ${stringifyEsmImportSpecifier(resolvePackageSourceFilePath("src/internal/workflow/queue-namespace.ts"))};`,
    "",
    `installEveWorkflowQueueNamespace(${JSON.stringify(agentName)});`,
    "",
    moduleMapSource,
    "",
    `const metadata = ${JSON.stringify(input.metadata, null, 2)};`,
    "",
    `const manifest = ${JSON.stringify(input.compileResult.manifest, null, 2)};`,
    "",
    "export function installCompiledArtifactsBootstrap() {",
    "  installBundledCompiledArtifacts({",
    "    manifest,",
    "    metadata,",
    "    moduleMap,",
    "  });",
    "}",
    "",
    "installCompiledArtifactsBootstrap();",
    "",
    "// Default export satisfies the Nitro plugin contract so this file",
    "// can be used directly as a Nitro plugin without a separate wrapper.",
    "export default function installCompiledArtifactsPlugin() {",
    "  // Already installed on import above.",
    "}",
    "",
    "export async function __eveInstallCompiledArtifactsStep() {",
    '  "use step";',
    "  return null;",
    "}",
    "",
  ].join("\n");
}

export function createWorkflowWorldPluginSource(
  configuredWorld: AgentWorkflowWorldDefinition | undefined,
  compiledArtifactsBootstrapPath?: string,
): string {
  const packageName = getWorldImport(
    configuredWorld === undefined
      ? process.env
      : { ...process.env, WORKFLOW_TARGET_WORLD: configuredWorld },
  );
  const importSpecifier =
    packageName === "@workflow/world-local" || packageName === "@workflow/world-vercel"
      ? resolvePackageCompiledFilePath(`src/compiled/${packageName}/index.js`)
      : packageName;
  const workflowRuntimeImportSpecifier = resolvePackageCompiledFilePath(
    "src/compiled/@workflow/core/runtime.js",
  );
  const workflowWorldValidationImportSpecifier = resolvePackageSourceFilePath(
    "src/internal/workflow/validate-world.ts",
  );

  return [
    "// Generated by eve. Do not edit by hand.",
    ...(compiledArtifactsBootstrapPath === undefined
      ? []
      : [`import ${stringifyEsmImportSpecifier(compiledArtifactsBootstrapPath)};`]),
    `import * as workflowWorldModule from ${stringifyEsmImportSpecifier(importSpecifier)};`,
    `import { createWorldFromModule, getWorld, setWorld } from ${stringifyEsmImportSpecifier(workflowRuntimeImportSpecifier)};`,
    `import { validateWorkflowWorld } from ${stringifyEsmImportSpecifier(workflowWorldValidationImportSpecifier)};`,
    "",
    "const workflowWorld = await createWorldFromModule(workflowWorldModule);",
    `validateWorkflowWorld({ packageName: ${JSON.stringify(configuredWorld)}, world: workflowWorld });`,
    "setWorld(workflowWorld);",
    "await getWorld();",
    "await workflowWorld.start?.();",
    "",
    "export default function installWorkflowWorldPlugin() {}",
    "",
  ].join("\n");
}

function createInstrumentationPluginSource(input: {
  agentName: string;
  instrumentationPath: string;
  registerConfigPath: string;
}): string {
  return [
    "// Generated by eve. Do not edit by hand.",
    `import * as instrumentationModule from ${stringifyEsmImportSpecifier(input.instrumentationPath)};`,
    `import { registerInstrumentationConfig } from ${stringifyEsmImportSpecifier(input.registerConfigPath)};`,
    "",
    "if (instrumentationModule.default != null) {",
    `  registerInstrumentationConfig(instrumentationModule.default, { agentName: ${JSON.stringify(input.agentName)} });`,
    "}",
    "",
    "// Default export satisfies the Nitro plugin contract so this file",
    "// can be used directly as a Nitro plugin without a separate wrapper.",
    "export default function installInstrumentationPlugin() {}",
    "",
  ].join("\n");
}
