#!/usr/bin/env node
import { existsSync } from "node:fs";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRequire } from "node:module";
import { format } from "oxfmt";

const require = createRequire(import.meta.url);
const extractorRequire = createRequire(require.resolve("@microsoft/api-extractor/package.json"));
const ts = extractorRequire("typescript");

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const header = "// Generated by pnpm run migratew --sync. Do not edit.\n";
const wireRoot = "packages/eve/src/execution/wire";

async function formatted(path, source) {
  const result = await format(path, source, {});
  if (result.errors.length)
    throw new Error(`Cannot format ${path}: ${JSON.stringify(result.errors)}`);
  return result.code;
}

function parse(path, source) {
  return ts.createSourceFile(path, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
}

function exportedVariable(ast, name) {
  return ast.statements
    .flatMap((statement) =>
      ts.isVariableStatement(statement) &&
      statement.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)
        ? [...statement.declarationList.declarations]
        : [],
    )
    .find((declaration) => ts.isIdentifier(declaration.name) && declaration.name.text === name);
}

/** Keep only the migration and its dependencies; schema construction stays server-side. */
export function extractMigration(path, source, name) {
  const ast = parse(path, source);
  const root = exportedVariable(ast, name);
  if (!root) throw new Error(`${path} must export ${name}.`);
  const host = ts.createCompilerHost({});
  host.getSourceFile = (file) => (file === path ? ast : undefined);
  const program = ts.createProgram([path], { noResolve: true, noLib: true }, host);
  const checker = program.getTypeChecker();
  const declarations = new Map();
  for (const statement of ast.statements) {
    if (ts.isImportDeclaration(statement)) {
      const clause = statement.importClause;
      if (!clause)
        throw new Error(`${path}: side-effect imports are not supported in migration modules.`);
      if (clause.name) declarations.set(checker.getSymbolAtLocation(clause.name), clause);
      const bindings = clause.namedBindings;
      if (bindings && ts.isNamespaceImport(bindings))
        declarations.set(checker.getSymbolAtLocation(bindings.name), bindings);
      if (bindings && ts.isNamedImports(bindings)) {
        for (const binding of bindings.elements)
          declarations.set(checker.getSymbolAtLocation(binding.name), binding);
      }
    } else if (ts.isVariableStatement(statement)) {
      for (const declaration of statement.declarationList.declarations) {
        const bind = (node) => {
          if (ts.isIdentifier(node))
            declarations.set(checker.getSymbolAtLocation(node), declaration);
          ts.forEachChild(node, bind);
        };
        bind(declaration.name);
      }
    } else if (statement.name) {
      declarations.set(checker.getSymbolAtLocation(statement.name), statement);
    } else {
      throw new Error(
        `${path}: use declarations only; migration modules cannot run top-level statements.`,
      );
    }
  }
  const selected = new Set();
  const collect = (declaration) => {
    if (selected.has(declaration)) return;
    if (ts.isImportClause(declaration) || ts.isNamespaceImport(declaration)) {
      throw new Error(`${path}: up/down dependencies must use named imports.`);
    }
    if (declaration === exportedVariable(ast, "schema")) {
      throw new Error(`${path}: up/down must not depend on schema construction. Use Wire types.`);
    }
    selected.add(declaration);
    const visit = (node) => {
      if (ts.isIdentifier(node)) {
        const symbol = ts.isShorthandPropertyAssignment(node.parent)
          ? checker.getShorthandAssignmentValueSymbol(node.parent)
          : checker.getSymbolAtLocation(node);
        const dependency = declarations.get(symbol);
        if (dependency) collect(dependency);
      }
      ts.forEachChild(node, visit);
    };
    if (!ts.isImportSpecifier(declaration)) visit(declaration);
  };
  collect(root);
  const printer = ts.createPrinter();
  const output = [];
  for (const statement of ast.statements) {
    let node = statement;
    if (ts.isImportDeclaration(statement)) {
      const clause = statement.importClause;
      const bindings = clause?.namedBindings;
      if (!bindings || !ts.isNamedImports(bindings)) continue;
      const used = bindings.elements.filter((binding) => selected.has(binding));
      if (!used.length) continue;
      const specifier = statement.moduleSpecifier.text;
      const typeOnly = clause.isTypeOnly || used.every((binding) => binding.isTypeOnly);
      const safeValues = new Map([
        ["#execution/wire/session-inbox-contract.js", ["SessionInboxWireError"]],
        ["#shared/guards.js", ["isObject"]],
      ]);
      if (
        !typeOnly &&
        !used.every(
          (binding) =>
            binding.isTypeOnly ||
            safeValues.get(specifier)?.includes(binding.propertyName?.text ?? binding.name.text),
        )
      ) {
        throw new Error(`${path}: migration runtime import ${specifier} is not workflow-safe.`);
      }
      if (!specifier.startsWith("#"))
        throw new Error(`${path}: migration dependencies must use # imports.`);
      node = ts.factory.updateImportDeclaration(
        statement,
        statement.modifiers,
        ts.factory.updateImportClause(
          clause,
          clause.isTypeOnly,
          undefined,
          ts.factory.updateNamedImports(bindings, used),
        ),
        statement.moduleSpecifier,
        statement.attributes,
      );
    } else if (ts.isVariableStatement(statement)) {
      const used = statement.declarationList.declarations.filter((declaration) =>
        selected.has(declaration),
      );
      if (!used.length) continue;
      node = ts.factory.updateVariableStatement(
        statement,
        statement.modifiers,
        ts.factory.updateVariableDeclarationList(statement.declarationList, used),
      );
    } else if (!selected.has(statement)) continue;
    output.push(printer.printNode(ts.EmitHint.Unspecified, node, ast));
  }
  return output.join("\n");
}

export async function discover(root, family) {
  if (family !== "session-inbox")
    throw new Error(`Unknown wire family ${JSON.stringify(family)}. Supported: session-inbox.`);
  const directory = join(root, wireRoot);
  const migrationsDir = join(directory, family, "migrations");
  const schemas = new Map();
  for (const name of await readdir(directory)) {
    const match = name.match(/^session-inbox-wire\.v([1-9]\d*)\.ts$/);
    if (match)
      schemas.set(Number(match[1]), {
        module: `#execution/wire/${name.replace(/\.ts$/, ".js")}`,
        name: `sessionInboxWireV${match[1]}Schema`,
      });
  }
  const migrations = [];
  for (const name of (await readdir(migrationsDir)).sort()) {
    const match = name.match(/^v(\d+)-to-v(\d+)\.ts$/);
    if (!match) continue;
    const from = Number(match[1]);
    const to = Number(match[2]);
    const path = join(migrationsDir, name);
    if (to !== from + 1) throw new Error(`${name}: migrations must connect adjacent versions.`);
    if (!existsSync(path.replace(/\.ts$/, ".test.ts")))
      throw new Error(`${name}: missing migration test.`);
    const source = await readFile(path, "utf8");
    const ast = parse(path, source);
    const combined = exportedVariable(ast, "schema") !== undefined;
    const exportName = combined ? "migration" : `v${from}ToV${to}`;
    const declaration = exportedVariable(ast, exportName);
    let initializer = declaration?.initializer;
    while (initializer && (ts.isSatisfiesExpression(initializer) || ts.isAsExpression(initializer)))
      initializer = initializer.expression;
    for (const [key, expected] of [
      ["from", from],
      ["to", to],
    ]) {
      const property =
        initializer &&
        ts.isObjectLiteralExpression(initializer) &&
        initializer.properties.find((entry) => entry.name?.getText(ast) === key);
      if (
        !property ||
        !ts.isPropertyAssignment(property) ||
        property.initializer.getText(ast) !== String(expected)
      )
        throw new Error(`${name}: ${key} must be the literal ${expected}.`);
    }
    if (combined) {
      if (schemas.has(to)) throw new Error(`Duplicate schema for wire version ${to}.`);
      schemas.set(to, {
        module: `#execution/wire/${family}/migrations/${name.replace(/\.ts$/, ".js")}`,
        name: "schema",
      });
    }
    migrations.push({ from, to, exportName, source, path, combined, name });
  }
  const versions = [...schemas.keys()].sort((a, b) => a - b);
  if (!versions.length || versions.some((v, i) => v !== i + 1))
    throw new Error("Wire schemas must be contiguous from version 1.");
  migrations.sort((a, b) => a.from - b.from);
  if (migrations.length !== versions.length - 1 || migrations.some((m, i) => m.from !== i + 1))
    throw new Error("Each wire version needs exactly one adjacent migration.");
  return { schemas, versions, migrations, directory, migrationsDir };
}

export async function generateCatalog(root, family, check = false) {
  const catalog = await discover(root, family);
  const { schemas, versions, migrations, directory } = catalog;
  const generated = join(directory, family, "generated");
  const outputs = new Map();
  const imports = migrations.map((m) => {
    const area = m.combined ? "generated" : "migrations";
    if (m.combined)
      outputs.set(join(generated, m.name), extractMigration(m.path, m.source, m.exportName));
    return `import { ${m.exportName === `v${m.from}ToV${m.to}` ? m.exportName : `${m.exportName} as v${m.from}ToV${m.to}`} } from "#execution/wire/${family}/${area}/${m.name.replace(/\.ts$/, ".js")}";`;
  });
  outputs.set(
    join(generated, "catalog.ts"),
    `${imports.join("\n")}
export const migrations = [${migrations.map((m) => `v${m.from}ToV${m.to}`).join(", ")}] as const;
`,
  );
  outputs.set(
    join(generated, "versions.ts"),
    `import type { z } from "#compiled/zod/index.js";
${versions.map((v) => `import type { ${schemas.get(v).name} as schemaV${v} } from "${schemas.get(v).module}";`).join("\n")}
export const versions = [${versions.join(", ")}] as const;
export const currentVersion = ${versions.at(-1)};
export interface WireVersions {
${versions.map((v) => `  ${v}: z.infer<typeof schemaV${v}>;`).join("\n")}
}
export type CurrentWire = WireVersions[typeof currentVersion];
`,
  );
  outputs.set(
    join(generated, "schemas.ts"),
    `${versions.map((v) => `import { ${schemas.get(v).name} as schemaV${v} } from "${schemas.get(v).module}";`).join("\n")}
export const schemas = { ${versions.map((v) => `${v}: schemaV${v}`).join(", ")} } as const;
export const currentSchema = schemas[${versions.at(-1)}];
`,
  );
  const stale = [];
  for (const [path, source] of outputs) {
    const content = await formatted(path, header + source);
    if ((await readFile(path, "utf8").catch(() => undefined)) === content) continue;
    if (check) stale.push(path);
    else {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, content);
    }
  }
  for (const name of await readdir(generated).catch(() => [])) {
    const path = join(generated, name);
    if (outputs.has(path)) continue;
    if (!(await readFile(path, "utf8")).startsWith(header)) {
      throw new Error(`Unexpected authored file in generated directory: ${path}`);
    }
    if (check) stale.push(path);
    else await rm(path);
  }
  if (stale.length)
    throw new Error(`Wire catalog is stale. Run pnpm run migratew --sync.\n${stale.join("\n")}`);
  return catalog;
}

export async function scaffold(root, family) {
  const catalog = await discover(root, family);
  const from = catalog.versions.at(-1);
  const to = from + 1;
  const previous = catalog.schemas.get(from);
  const path = join(catalog.migrationsDir, `v${from}-to-v${to}.ts`);
  const testPath = path.replace(/\.ts$/, ".test.ts");
  if (existsSync(path) || existsSync(testPath))
    throw new Error(`Migration v${from} to v${to} already exists.`);
  const migration = `import { z } from "#compiled/zod/index.js";
import { ${previous.name} as previousSchema } from "${previous.module}";
import type { Migration } from "#execution/wire/${family}/migration.js";

const version = z.literal(${to});
// Define the new contract here. Existing contracts remain frozen.
const [first, ...rest] = previousSchema.options;
export const schema = z.discriminatedUnion("kind", [
  first.extend({ version }),
  ...rest.map((option) => option.extend({ version })),
]);

export const migration = {
  from: ${from},
  to: ${to},
  up: (wire) => ({ ...wire, version: ${to} }),
  down: (wire) => ({ ...wire, version: ${from} }),
} satisfies Migration<${from}, ${to}>;
`;
  const test = `import { expect, it } from "vitest";
import { migration, schema } from "./v${from}-to-v${to}.js";
import { ${previous.name} as previousSchema } from "${previous.module}";

it("preserves an ordinary cancellation in both directions", () => {
  const before = previousSchema.parse({ kind: "cancel", version: ${from}, turnId: "turn-1" });
  const after = migration.up(before);
  expect(schema.parse(after)).toEqual({ ...before, version: ${to} });
  expect(previousSchema.parse(migration.down(after))).toEqual(before);
});

it("covers the protocol change", () => {
  throw new Error("Replace this test with an example of the new field or operation, including downgrade behavior.");
});
`;
  await writeFile(path, await formatted(path, migration), { flag: "wx" });
  await writeFile(testPath, await formatted(testPath, test), { flag: "wx" });
  await generateCatalog(root, family);
  return { path, testPath };
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const [argument, extra] = process.argv.slice(2);
  try {
    if (extra) throw new Error("Usage: pnpm run migratew session-inbox | --sync | --check");
    if (argument === "--sync" || argument === "--check") {
      await generateCatalog(repoRoot, "session-inbox", argument === "--check");
      console.log(argument === "--check" ? "Wire catalog is current." : "Wire catalog updated.");
    } else {
      const result = await scaffold(repoRoot, argument);
      console.log(
        `Created ${result.path}\nCreated ${result.testPath}\nDefine the schema and conversions, then replace the failing example test.\nRun pnpm run migratew --sync after editing the migration.`,
      );
    }
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
