import { readFile } from "node:fs/promises";
import { join } from "node:path";

import { DEFAULT_EVE_CHANNEL_TEMPLATE, DEFAULT_TSCONFIG_TEMPLATE } from "../create/project.js";
import { WEB_APP_TEMPLATE_FILES } from "../create/web-template.js";
import { pathExists, writeTextFile } from "../files.js";

export const WEB_CHANNEL_PATH = "agent/channels/eve.ts";
export const WEB_NEXT_CONFIG_PATH = "next.config.ts";
export const WEB_VERCEL_JSON_PATH = "vercel.json";

const WEB_TSCONFIG_PATH = "tsconfig.json";
const WEB_VERCEL_JSON_SCHEMA = "https://openapi.vercel.sh/vercel.json";
const SUPPORTED_NEXT_CONFIG_PATHS = [
  "next.config.js",
  "next.config.mjs",
  WEB_NEXT_CONFIG_PATH,
  "next.config.mts",
] as const;
const WEB_COMPETING_NEXT_CONFIG_PATHS = SUPPORTED_NEXT_CONFIG_PATHS.filter(
  (path) => path !== WEB_NEXT_CONFIG_PATH,
);

export function renderWebAppTemplate(content: string, appName: string): string {
  return content
    .replaceAll("__EVE_INIT_APP_NAME__", appName)
    .replaceAll("__EVE_INIT_WITH_EVE_OPTIONS__", "");
}

export async function reconcileRegistryInstalledWebChannel(
  projectRoot: string,
  appName: string,
): Promise<{ action: "created" | "overwritten" | "skipped"; filePath: string }> {
  const filePath = join(projectRoot, WEB_CHANNEL_PATH);
  const channelExists = await pathExists(filePath);
  const existingChannel = channelExists ? await readFile(filePath, "utf8") : undefined;

  // Exact equality is the ownership boundary: any user edit preserves the file.
  if (existingChannel !== undefined && existingChannel !== DEFAULT_EVE_CHANNEL_TEMPLATE) {
    return { action: "skipped", filePath };
  }

  await writeTextFile(
    filePath,
    renderWebAppTemplate(WEB_APP_TEMPLATE_FILES[WEB_CHANNEL_PATH], appName),
    { force: true },
  );
  return { action: channelExists ? "overwritten" : "created", filePath };
}

/**
 * Creates the Web Chat tsconfig or replaces the untouched eve base config.
 * Any user-authored configuration remains owned by the app.
 */
export async function reconcileRegistryInstalledWebTsconfig(
  projectRoot: string,
): Promise<{ action: "created" | "overwritten" | "skipped"; filePath: string }> {
  const filePath = join(projectRoot, WEB_TSCONFIG_PATH);
  const tsconfigExists = await pathExists(filePath);
  const existingTsconfig = tsconfigExists ? await readFile(filePath, "utf8") : undefined;

  if (existingTsconfig !== undefined && existingTsconfig !== DEFAULT_TSCONFIG_TEMPLATE) {
    return { action: "skipped", filePath };
  }

  await writeTextFile(filePath, WEB_APP_TEMPLATE_FILES[WEB_TSCONFIG_PATH], {
    force: true,
  });
  return { action: tsconfigExists ? "overwritten" : "created", filePath };
}

/**
 * Ensure the Next.js web channel has a minimal `vercel.json`.
 *
 * The eve service and its `/eve/v1/*` routes are generated by `withEve()` into
 * `.vercel/output/config.json` at build time. An existing file remains
 * user-owned because the scaffold has nothing to add to it.
 */
export async function ensureWebVercelJson(filePath: string): Promise<"skipped" | "written"> {
  if (await pathExists(filePath)) {
    return "skipped";
  }

  await writeTextFile(
    filePath,
    `${JSON.stringify({ $schema: WEB_VERCEL_JSON_SCHEMA }, null, 2)}\n`,
    {
      force: true,
    },
  );
  return "written";
}

export async function findCompetingNextConfigFiles(projectRoot: string): Promise<string[]> {
  const filePaths: string[] = [];
  for (const relativePath of WEB_COMPETING_NEXT_CONFIG_PATHS) {
    const filePath = join(projectRoot, relativePath);
    if (!(await pathExists(filePath))) continue;
    filePaths.push(filePath);
  }
  return filePaths;
}
