#!/usr/bin/env node
import { existsSync } from "node:fs";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRequire } from "node:module";
import { format } from "oxfmt";

const require = createRequire(import.meta.url);
const extractorRequire = createRequire(require.resolve("@microsoft/api-extractor/package.json"));
const ts = extractorRequire("typescript");

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const header = "// Generated by pnpm run migratew --sync. Do not edit.\n";
const wireRoot = "src/execution/wire";

async function formatted(path, source) {
  const result = await format(path, source, {});
  if (result.errors.length)
    throw new Error(`Cannot format ${path}: ${JSON.stringify(result.errors)}`);
  return result.code;
}

function parse(path, source) {
  return ts.createSourceFile(path, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
}

function exportedVariable(ast, name) {
  return ast.statements
    .flatMap((statement) =>
      ts.isVariableStatement(statement) &&
      statement.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)
        ? [...statement.declarationList.declarations]
        : [],
    )
    .find((declaration) => ts.isIdentifier(declaration.name) && declaration.name.text === name);
}

export async function discover(packageRoot, family) {
  if (family !== "session-inbox")
    throw new Error(`Unknown wire family ${JSON.stringify(family)}. Supported: session-inbox.`);
  const directory = join(packageRoot, wireRoot, family);
  const migrationsDir = join(directory, "migrations");
  const schemas = new Map();
  for (const name of await readdir(directory)) {
    const match = name.match(/^session-inbox-wire\.v([1-9]\d*)\.ts$/);
    if (match)
      schemas.set(Number(match[1]), {
        module: `#execution/wire/${family}/${name.replace(/\.ts$/, ".js")}`,
        name: `sessionInboxWireV${match[1]}Schema`,
      });
  }
  const entries = (await readdir(migrationsDir)).sort();
  for (const name of entries) {
    const match = name.match(/^v([1-9]\d*)\.schema\.ts$/);
    if (!match) continue;
    const version = Number(match[1]);
    if (schemas.has(version)) throw new Error(`Duplicate schema for wire version ${version}.`);
    schemas.set(version, {
      module: `#execution/wire/${family}/migrations/${name.replace(/\.ts$/, ".js")}`,
      name: "schema",
    });
  }
  const migrations = [];
  for (const name of entries) {
    const match = name.match(/^v(\d+)-to-v(\d+)\.ts$/);
    if (!match) continue;
    const from = Number(match[1]);
    const to = Number(match[2]);
    const path = join(migrationsDir, name);
    if (to !== from + 1) throw new Error(`${name}: migrations must connect adjacent versions.`);
    if (!existsSync(path.replace(/\.ts$/, ".test.ts")))
      throw new Error(`${name}: missing migration test.`);
    const source = await readFile(path, "utf8");
    const ast = parse(path, source);
    const exportName = `v${from}ToV${to}`;
    const declaration = exportedVariable(ast, exportName);
    let initializer = declaration?.initializer;
    while (initializer && (ts.isSatisfiesExpression(initializer) || ts.isAsExpression(initializer)))
      initializer = initializer.expression;
    for (const [key, expected] of [
      ["from", from],
      ["to", to],
    ]) {
      const property =
        initializer &&
        ts.isObjectLiteralExpression(initializer) &&
        initializer.properties.find((entry) => entry.name?.getText(ast) === key);
      if (
        !property ||
        !ts.isPropertyAssignment(property) ||
        property.initializer.getText(ast) !== String(expected)
      )
        throw new Error(`${name}: ${key} must be the literal ${expected}.`);
    }
    migrations.push({ from, to, exportName, name });
  }
  const versions = [...schemas.keys()].sort((a, b) => a - b);
  if (!versions.length || versions.some((v, i) => v !== i + 1))
    throw new Error("Wire schemas must be contiguous from version 1.");
  migrations.sort((a, b) => a.from - b.from);
  if (migrations.length !== versions.length - 1 || migrations.some((m, i) => m.from !== i + 1))
    throw new Error("Each wire version needs exactly one adjacent migration.");
  return { schemas, versions, migrations, directory, migrationsDir };
}

export async function generateCatalog(packageRoot, family, check = false) {
  const catalog = await discover(packageRoot, family);
  const { schemas, versions, migrations, directory } = catalog;
  const generated = join(directory, "generated");
  const outputs = new Map();
  const imports = migrations.map(
    (m) =>
      `import { ${m.exportName} } from "#execution/wire/${family}/migrations/${m.name.replace(/\.ts$/, ".js")}";`,
  );
  outputs.set(
    join(generated, "catalog.ts"),
    `${imports.join("\n")}
export const migrations = [${migrations.map((m) => `v${m.from}ToV${m.to}`).join(", ")}] as const;
`,
  );
  outputs.set(
    join(generated, "versions.ts"),
    `import type { z } from "#compiled/zod/index.js";
${versions.map((v) => `import type { ${schemas.get(v).name} as schemaV${v} } from "${schemas.get(v).module}";`).join("\n")}
export const versions = [${versions.join(", ")}] as const;
export const currentVersion = ${versions.at(-1)};
export interface WireVersions {
${versions.map((v) => `  ${v}: z.infer<typeof schemaV${v}>;`).join("\n")}
}
export type CurrentWire = WireVersions[typeof currentVersion];
`,
  );
  outputs.set(
    join(generated, "schemas.ts"),
    `${versions.map((v) => `import { ${schemas.get(v).name} as schemaV${v} } from "${schemas.get(v).module}";`).join("\n")}
export const schemas = { ${versions.map((v) => `${v}: schemaV${v}`).join(", ")} } as const;
export const currentSchema = schemas[${versions.at(-1)}];
`,
  );
  const stale = [];
  for (const [path, source] of outputs) {
    const content = await formatted(path, header + source);
    if ((await readFile(path, "utf8").catch(() => undefined)) === content) continue;
    if (check) stale.push(path);
    else {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, content);
    }
  }
  for (const name of await readdir(generated).catch(() => [])) {
    const path = join(generated, name);
    if (outputs.has(path)) continue;
    if (!(await readFile(path, "utf8")).startsWith(header)) {
      throw new Error(`Unexpected authored file in generated directory: ${path}`);
    }
    if (check) stale.push(path);
    else await rm(path);
  }
  if (stale.length)
    throw new Error(`Wire catalog is stale. Run pnpm run migratew --sync.\n${stale.join("\n")}`);
  return catalog;
}

export async function scaffold(packageRoot, family) {
  const catalog = await discover(packageRoot, family);
  const from = catalog.versions.at(-1);
  const to = from + 1;
  const previous = catalog.schemas.get(from);
  const path = join(catalog.migrationsDir, `v${from}-to-v${to}.ts`);
  const testPath = path.replace(/\.ts$/, ".test.ts");
  const schemaPath = join(catalog.migrationsDir, `v${to}.schema.ts`);
  if ([schemaPath, path, testPath].some(existsSync))
    throw new Error(`Migration v${from} to v${to} already exists.`);
  const schema = `import { z } from "#compiled/zod/index.js";
import { ${previous.name} as previousSchema } from "${previous.module}";
const version = z.literal(${to});
// Define the new contract here. Existing contracts remain frozen.
const [first, ...rest] = previousSchema.options;
export const schema = z.discriminatedUnion("kind", [
  first.extend({ version }),
  ...rest.map((option) => option.extend({ version })),
]);
`;
  const migration = `import type { Migration } from "#execution/wire/${family}/migration.js";

export const v${from}ToV${to} = {
  from: ${from},
  to: ${to},
  up: (wire) => ({ ...wire, version: ${to} }),
  down: (wire) => ({ ...wire, version: ${from} }),
} satisfies Migration<${from}, ${to}>;
`;
  const test = `import { expect, it } from "vitest";
import { v${from}ToV${to} as migration } from "./v${from}-to-v${to}.js";
import { schema } from "./v${to}.schema.js";
import { ${previous.name} as previousSchema } from "${previous.module}";

it("preserves an ordinary cancellation in both directions", () => {
  const before = previousSchema.parse({ kind: "cancel", version: ${from}, turnId: "turn-1" });
  const after = migration.up(before);
  expect(schema.parse(after)).toEqual({ ...before, version: ${to} });
  expect(previousSchema.parse(migration.down(after))).toEqual(before);
});

it("covers the protocol change", () => {
  throw new Error("Replace this test with an example of the new field or operation, including downgrade behavior.");
});
`;
  await writeFile(schemaPath, await formatted(schemaPath, schema), { flag: "wx" });
  await writeFile(path, await formatted(path, migration), { flag: "wx" });
  await writeFile(testPath, await formatted(testPath, test), { flag: "wx" });
  await generateCatalog(packageRoot, family);
  return { schemaPath, path, testPath };
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const [argument, extra] = process.argv.slice(2);
  try {
    if (extra) throw new Error("Usage: pnpm run migratew session-inbox | --sync | --check");
    if (argument === "--sync" || argument === "--check") {
      await generateCatalog(packageRoot, "session-inbox", argument === "--check");
      console.log(argument === "--check" ? "Wire catalog is current." : "Wire catalog updated.");
    } else {
      const result = await scaffold(packageRoot, argument);
      console.log(
        `Created ${result.schemaPath}\nCreated ${result.path}\nCreated ${result.testPath}\nDefine the schema and conversions, then replace the failing example test.\nRun pnpm run migratew --sync after editing the migration.`,
      );
    }
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
