import { z } from "#compiled/zod/index.js";
import type {
  CompiledAgentManifest,
  CompiledAgentNodeManifest,
  CompiledAgentResources,
} from "#compiler/manifest.js";
import { ROOT_COMPILED_AGENT_NODE_ID } from "#compiler/manifest.js";
import { assertTotalModuleBindings } from "#compiler/module-binding.js";
import { collectModuleRefsForManifest } from "#compiler/module-references.js";
import type { ModuleSourceRef } from "#shared/source-ref.js";
import { normalizeEsmImportSpecifier } from "#internal/application/import-specifier.js";

/**
 * Compiled module ownership for one runtime graph node.
 */
export type CompiledModuleNodeScope = z.infer<typeof compiledModuleNodeScopeSchema>;

/**
 * Flattened compiled authored module map keyed by stable node ids.
 */
export type CompiledModuleMap = z.infer<typeof compiledModuleMapSchema>;

const compiledModuleNodeScopeSchema = z
  .object({
    modules: z.record(z.string(), z.object({}).passthrough()),
  })
  .strict();

/**
 * Zod schema for the flattened compiled authored module map.
 */
export const compiledModuleMapSchema = z
  .object({
    nodes: z.record(z.string(), compiledModuleNodeScopeSchema),
  })
  .strict();

/**
 * Input for generating the compiled authored module map artifact.
 */
export interface CreateCompiledModuleMapSourceInput {
  /**
   * Controls how generated authored-module imports are written. Relative
   * specifiers are the compiler default; absolute specifiers are useful when a
   * bundler consumes the module map from a virtual module id.
   */
  importSpecifierStyle?: "absolute" | "relative";
  manifest: CompiledAgentManifest;
  moduleMapPath: string;
  programmaticRegistryImports?: Readonly<
    Record<string, { readonly exportName: string; readonly importSpecifier: string }>
  >;
}

interface CollectedModuleImport {
  readonly bindingName: string;
  readonly importStatement: string;
  readonly moduleExpression: string;
  readonly sourceId: string;
}

interface CollectedModuleNodeScope {
  readonly modules: readonly CollectedModuleImport[];
  readonly nodeId: string;
}

/**
 * Generates the compiler-owned module map artifact that statically imports
 * every module-backed authored source.
 */
export function createCompiledModuleMapSource(input: CreateCompiledModuleMapSourceInput): string {
  const moduleMapDirectory = dirnameFilesystemPath(input.moduleMapPath);
  const importSpecifierStyle = input.importSpecifierStyle ?? "relative";
  let nextBindingIndex = 0;
  const collectedScopes: CollectedModuleNodeScope[] = [
    collectModuleNodeScope({
      importSpecifierStyle,
      manifest: input.manifest,
      moduleMapDirectory,
      nextBindingName() {
        return `module_${nextBindingIndex++}`;
      },
      nodeId: ROOT_COMPILED_AGENT_NODE_ID,
      programmaticRegistryImports: input.programmaticRegistryImports,
    }),
    ...[...input.manifest.subagents]
      .sort((left, right) => left.nodeId.localeCompare(right.nodeId))
      .map((subagent) =>
        collectModuleNodeScope({
          importSpecifierStyle,
          manifest: subagent.agent,
          additionalModuleRef: subagent.configResolver,
          moduleMapDirectory,
          nextBindingName() {
            return `module_${nextBindingIndex++}`;
          },
          nodeId: subagent.nodeId,
          programmaticRegistryImports: input.programmaticRegistryImports,
        }),
      ),
  ];
  const allModules = collectedScopes.flatMap((scope) => scope.modules);

  const staticImports = allModules.map((moduleImport) => moduleImport.importStatement);

  return [
    "// Generated by eve. Do not edit by hand.",
    "",
    ...staticImports,
    ...(staticImports.length > 0 ? [""] : []),
    `export const moduleMap = ${renderModuleMap(collectedScopes)};`,
    "",
    "export default moduleMap;",
    "",
  ].join("\n");
}

function collectModuleNodeScope(input: {
  readonly additionalModuleRef?: ModuleSourceRef;
  readonly importSpecifierStyle: "absolute" | "relative";
  readonly manifest: CompiledAgentNodeManifest | CompiledAgentResources;
  readonly moduleMapDirectory: string;
  readonly nextBindingName: () => string;
  readonly nodeId: string;
  readonly programmaticRegistryImports?: CreateCompiledModuleMapSourceInput["programmaticRegistryImports"];
}): CollectedModuleNodeScope {
  assertTotalModuleBindings({
    additionalRefs: input.additionalModuleRef === undefined ? [] : [input.additionalModuleRef],
    bindings: input.manifest.bindings,
    manifest: input.manifest,
    nodeId: input.nodeId,
  });

  return {
    modules: [
      ...collectModuleRefsForManifest(input.manifest),
      ...(input.additionalModuleRef === undefined ? [] : [input.additionalModuleRef]),
    ]
      .sort((left, right) => left.sourceId.localeCompare(right.sourceId))
      .map((moduleSourceRef) =>
        collectModuleImport({
          binding: input.manifest.bindings[moduleSourceRef.sourceId]!,
          bindingName: input.nextBindingName(),
          importSpecifierStyle: input.importSpecifierStyle,
          moduleMapDirectory: input.moduleMapDirectory,
          nodeId: input.nodeId,
          programmaticRegistryImports: input.programmaticRegistryImports,
          sourceId: moduleSourceRef.sourceId,
        }),
      ),
    nodeId: input.nodeId,
  };
}

export { collectModuleRefsForManifest } from "#compiler/module-references.js";

function collectModuleImport(input: {
  readonly binding: CompiledAgentResources["bindings"][string];
  readonly bindingName: string;
  readonly importSpecifierStyle: "absolute" | "relative";
  readonly moduleMapDirectory: string;
  readonly nodeId: string;
  readonly programmaticRegistryImports?: CreateCompiledModuleMapSourceInput["programmaticRegistryImports"];
  readonly sourceId: string;
}): CollectedModuleImport {
  if (input.binding.backing.kind === "filesystem") {
    const importSpecifier = createImportSpecifier({
      fromDirectory: input.moduleMapDirectory,
      importSpecifierStyle: input.importSpecifierStyle,
      targetPath: input.binding.backing.sourcePath,
    });
    return {
      bindingName: input.bindingName,
      importStatement: `import * as ${input.bindingName} from ${JSON.stringify(importSpecifier)};`,
      moduleExpression: input.bindingName,
      sourceId: input.sourceId,
    };
  }

  const registryImport = input.programmaticRegistryImports?.[input.binding.backing.registryId];
  if (registryImport === undefined) {
    throw new Error(
      `Cannot generate programmatic binding "${input.sourceId}" on compiled node "${input.nodeId}" because registry "${input.binding.backing.registryId}" has no static import.`,
    );
  }
  return {
    bindingName: input.bindingName,
    importStatement: `import { ${registryImport.exportName} as ${input.bindingName} } from ${JSON.stringify(registryImport.importSpecifier)};`,
    moduleExpression: `${input.bindingName}.getModule(${JSON.stringify(input.binding.backing)}).namespace`,
    sourceId: input.sourceId,
  };
}

function createImportSpecifier(input: {
  fromDirectory: string;
  importSpecifierStyle: "absolute" | "relative";
  targetPath: string;
}): string {
  if (input.importSpecifierStyle === "absolute") {
    return normalizeEsmImportSpecifier(normalizeFilesystemPath(input.targetPath));
  }

  const relativeSpecifier = relativeFilesystemPath(input.fromDirectory, input.targetPath);

  if (relativeSpecifier.startsWith(".")) {
    return relativeSpecifier;
  }

  return `./${relativeSpecifier}`;
}

function renderModuleMap(scopes: readonly CollectedModuleNodeScope[]): string {
  return renderFrozenObject(
    [
      {
        key: "nodes",
        value: renderFrozenObject(
          scopes.map((scope) => ({
            key: scope.nodeId,
            value: renderFrozenObject(
              [
                {
                  key: "modules",
                  value: renderFrozenObject(
                    scope.modules.map((moduleImport) => ({
                      key: moduleImport.sourceId,
                      value: moduleImport.moduleExpression,
                    })),
                  ),
                },
              ],
              3,
            ),
          })),
        ),
      },
    ],
    0,
  );
}

function renderFrozenObject(
  entries: ReadonlyArray<{
    key: string;
    value: string;
  }>,
  depth: number = 1,
): string {
  if (entries.length === 0) {
    return "Object.freeze({})";
  }

  const indentation = "  ".repeat(depth);
  const nestedIndentation = "  ".repeat(depth + 1);

  return [
    "Object.freeze({",
    entries
      .map((entry) => {
        return `${nestedIndentation}${JSON.stringify(entry.key)}: ${entry.value.replaceAll("\n", `\n${nestedIndentation}`)}`;
      })
      .join(",\n"),
    `${indentation}})`,
  ].join("\n");
}

function dirnameFilesystemPath(path: string): string {
  const parsed = splitFilesystemPath(path);

  if (parsed.segments.length === 0) {
    return parsed.root.length === 0 ? "." : parsed.root;
  }

  return createFilesystemPath(parsed.root, parsed.segments.slice(0, -1));
}

function relativeFilesystemPath(fromDirectory: string, targetPath: string): string {
  const from = splitFilesystemPath(fromDirectory);
  const target = splitFilesystemPath(targetPath);

  if (from.root !== target.root) {
    return normalizeFilesystemPath(targetPath);
  }

  let sharedIndex = 0;

  while (
    sharedIndex < from.segments.length &&
    sharedIndex < target.segments.length &&
    from.segments[sharedIndex] === target.segments[sharedIndex]
  ) {
    sharedIndex += 1;
  }

  const relativeSegments = [
    ...Array.from({ length: from.segments.length - sharedIndex }, () => ".."),
    ...target.segments.slice(sharedIndex),
  ];

  return relativeSegments.length === 0 ? "." : relativeSegments.join("/");
}

function normalizeFilesystemPath(path: string): string {
  const parsed = splitFilesystemPath(path);
  return createFilesystemPath(parsed.root, parsed.segments);
}

function splitFilesystemPath(path: string): {
  readonly root: string;
  readonly segments: string[];
} {
  const normalized = path.replaceAll("\\", "/");
  let root = "";
  let remainder = normalized;

  const windowsDriveMatch = normalized.match(/^[A-Za-z]:/);

  if (windowsDriveMatch !== null) {
    root = windowsDriveMatch[0];
    remainder = normalized.slice(root.length);

    if (remainder.startsWith("/")) {
      root = `${root}/`;
      remainder = remainder.slice(1);
    }
  } else if (normalized.startsWith("/")) {
    root = "/";
    remainder = normalized.slice(1);
  }

  const segments: string[] = [];

  for (const segment of remainder.split("/")) {
    if (segment.length === 0 || segment === ".") {
      continue;
    }

    if (segment === "..") {
      if (segments.length > 0 && segments[segments.length - 1] !== "..") {
        segments.pop();
        continue;
      }

      if (root.length === 0) {
        segments.push(segment);
      }

      continue;
    }

    segments.push(segment);
  }

  return {
    root,
    segments,
  };
}

function createFilesystemPath(root: string, segments: readonly string[]): string {
  if (root === "/") {
    return segments.length === 0 ? "/" : `/${segments.join("/")}`;
  }

  if (root.endsWith("/")) {
    return segments.length === 0 ? root : `${root}${segments.join("/")}`;
  }

  if (root.length > 0) {
    return segments.length === 0 ? root : `${root}/${segments.join("/")}`;
  }

  return segments.length === 0 ? "." : segments.join("/");
}
