import { z } from "#compiled/zod/index.js";
import type { ModuleSourceRef } from "#shared/source-ref.js";
import type {
  CompiledAgentManifest,
  CompiledAgentNodeManifest,
  CompiledAgentResources,
  CompiledExtensionMount,
} from "#compiler/manifest.js";
import { ROOT_COMPILED_AGENT_NODE_ID } from "#compiler/manifest.js";
import type { CompiledModuleBinding } from "#compiler/source-graph.js";
import { normalizeEsmImportSpecifier } from "#internal/application/import-specifier.js";

/**
 * Import specifier the generated module map uses to reach the framework's
 * statically registered programmatic sources. A bare specifier so app
 * bundlers externalize it like every other `eve/*` runtime import and the
 * process shares one framework registry instance; plain-node loads resolve
 * it from the application's `node_modules`.
 */
const PROGRAMMATIC_SOURCE_LOADER_SPECIFIER = "eve/internal/agent-sources";

/**
 * Compiled module ownership for one runtime graph node.
 */
export type CompiledModuleNodeScope = z.infer<typeof compiledModuleNodeScopeSchema>;

/**
 * Flattened compiled authored module map keyed by stable node ids.
 */
export type CompiledModuleMap = z.infer<typeof compiledModuleMapSchema>;

const compiledModuleNodeScopeSchema = z
  .object({
    modules: z.record(z.string(), z.object({}).passthrough()),
  })
  .strict();

/**
 * Zod schema for the flattened compiled authored module map.
 */
export const compiledModuleMapSchema = z
  .object({
    nodes: z.record(z.string(), compiledModuleNodeScopeSchema),
  })
  .strict();

/**
 * Input for generating the compiled authored module map artifact.
 */
export interface CreateCompiledModuleMapSourceInput {
  /**
   * Controls how generated authored-module imports are written. Relative
   * specifiers are the compiler default; absolute specifiers are useful when a
   * bundler consumes the module map from a virtual module id.
   */
  importSpecifierStyle?: "absolute" | "relative";
  manifest: CompiledAgentManifest;
  moduleMapPath: string;
}

type CollectedModuleImport =
  | {
      readonly bindingName: string;
      readonly importSpecifier: string;
      readonly kind: "static";
      readonly sourceId: string;
    }
  | {
      readonly bindingName: string;
      readonly kind: "programmatic";
      readonly moduleId: string;
      readonly registryId: string;
      readonly revision: string;
      readonly sourceId: string;
    };

interface CollectedModuleNodeScope {
  readonly modules: readonly CollectedModuleImport[];
  readonly nodeId: string;
}

/**
 * Generates the compiler-owned module map artifact. Filesystem-backed
 * sources become ordinary static imports of their exact binding source
 * paths; programmatic sources become statically reachable registry lookups
 * awaited at module evaluation. Only selected bindings are emitted, so a
 * shadowed source never loads at cold start.
 */
export function createCompiledModuleMapSource(input: CreateCompiledModuleMapSourceInput): string {
  const moduleMapDirectory = dirnameFilesystemPath(input.moduleMapPath);
  const importSpecifierStyle = input.importSpecifierStyle ?? "relative";
  let nextBindingIndex = 0;
  const collectedScopes: CollectedModuleNodeScope[] = [
    collectModuleNodeScope({
      importSpecifierStyle,
      manifest: input.manifest,
      moduleMapDirectory,
      nextBindingName() {
        return `module_${nextBindingIndex++}`;
      },
      nodeId: ROOT_COMPILED_AGENT_NODE_ID,
    }),
    ...[...input.manifest.subagents]
      .sort((left, right) => left.nodeId.localeCompare(right.nodeId))
      .map((subagent) =>
        collectModuleNodeScope({
          importSpecifierStyle,
          manifest: subagent.agent,
          additionalModuleRef: subagent.configResolver,
          moduleMapDirectory,
          nextBindingName() {
            return `module_${nextBindingIndex++}`;
          },
          nodeId: subagent.nodeId,
        }),
      ),
  ];
  const allModules = collectedScopes.flatMap((scope) => scope.modules);

  const staticImports = allModules.flatMap((moduleImport) =>
    moduleImport.kind === "static"
      ? [
          `import * as ${moduleImport.bindingName} from ${JSON.stringify(moduleImport.importSpecifier)};`,
        ]
      : [],
  );
  const programmaticImports = allModules.filter((entry) => entry.kind === "programmatic");
  const loaderImport =
    programmaticImports.length === 0
      ? []
      : [
          `import { loadFrameworkSourceModuleNamespace as __eveLoadProgrammaticModule } from ${JSON.stringify(PROGRAMMATIC_SOURCE_LOADER_SPECIFIER)};`,
        ];
  const programmaticBindings = programmaticImports.map(
    (entry) =>
      `const ${entry.bindingName} = await __eveLoadProgrammaticModule(${JSON.stringify(entry.registryId)}, ${JSON.stringify(entry.moduleId)}, ${JSON.stringify(entry.revision)});`,
  );

  return [
    "// Generated by eve. Do not edit by hand.",
    "",
    ...loaderImport,
    ...staticImports,
    ...(staticImports.length + loaderImport.length > 0 ? [""] : []),
    ...programmaticBindings,
    ...(programmaticBindings.length > 0 ? [""] : []),
    `export const moduleMap = ${renderModuleMap(collectedScopes)};`,
    "",
    "export default moduleMap;",
    "",
  ].join("\n");
}

function collectModuleNodeScope(input: {
  readonly additionalModuleRef?: ModuleSourceRef;
  readonly importSpecifierStyle: "absolute" | "relative";
  readonly manifest: CompiledAgentNodeManifest | CompiledAgentResources;
  readonly moduleMapDirectory: string;
  readonly nextBindingName: () => string;
  readonly nodeId: string;
}): CollectedModuleNodeScope {
  return {
    modules: [
      ...collectModuleRefsForManifest(input.manifest),
      ...(input.additionalModuleRef === undefined ? [] : [input.additionalModuleRef]),
    ]
      .sort((left, right) => left.sourceId.localeCompare(right.sourceId))
      .map((moduleSourceRef): CollectedModuleImport => {
        const binding = requireModuleBinding(
          input.manifest.bindings,
          moduleSourceRef,
          input.nodeId,
        );
        if (binding.backing.kind === "programmatic") {
          return {
            bindingName: input.nextBindingName(),
            kind: "programmatic",
            moduleId: binding.backing.moduleId,
            registryId: binding.backing.registryId,
            revision: binding.backing.revision,
            sourceId: moduleSourceRef.sourceId,
          };
        }
        return {
          bindingName: input.nextBindingName(),
          importSpecifier: createImportSpecifier({
            fromDirectory: input.moduleMapDirectory,
            importSpecifierStyle: input.importSpecifierStyle,
            targetPath: binding.backing.sourcePath,
          }),
          kind: "static",
          sourceId: moduleSourceRef.sourceId,
        };
      }),
    nodeId: input.nodeId,
  };
}

/**
 * Resolves the required compiled binding for one module-backed manifest
 * reference. Bindings are the only authority for module loading; a missing
 * binding is a malformed artifact.
 */
export function requireModuleBinding(
  bindings: Readonly<Record<string, CompiledModuleBinding>>,
  moduleSourceRef: Pick<ModuleSourceRef, "logicalPath" | "sourceId">,
  nodeId: string,
): CompiledModuleBinding {
  const binding = bindings[moduleSourceRef.sourceId];
  if (binding === undefined) {
    throw new Error(
      `Compiled node "${nodeId}" has no module binding for source "${moduleSourceRef.sourceId}" (${moduleSourceRef.logicalPath}).`,
    );
  }
  return binding;
}

/**
 * Collects every module-backed source reference from a single compiled
 * agent node manifest. Used by both the compiler (to generate the static
 * module-map artifact) and the runtime loader (to hydrate a module map
 * from the manifest when the pre-built artifact is unavailable).
 */
export function collectModuleRefsForManifest(
  manifest: CompiledAgentNodeManifest | CompiledAgentResources,
): ModuleSourceRef[] {
  const moduleSourceRefs = new Map<string, ModuleSourceRef>();

  if ("config" in manifest && manifest.config.source !== undefined) {
    moduleSourceRefs.set(manifest.config.source.sourceId, manifest.config.source);
  }

  if ("config" in manifest && manifest.config.model?.source !== undefined) {
    moduleSourceRefs.set(manifest.config.model.source.sourceId, manifest.config.model.source);
  }

  for (const channel of manifest.channels) {
    moduleSourceRefs.set(channel.sourceId, {
      exportName: channel.exportName,
      sourceKind: "module",
      logicalPath: channel.logicalPath,
      sourceId: channel.sourceId,
    });
  }

  for (const connection of manifest.connections) {
    moduleSourceRefs.set(connection.sourceId, {
      exportName: connection.exportName,
      sourceKind: "module",
      logicalPath: connection.logicalPath,
      sourceId: connection.sourceId,
    });
  }

  for (const tool of manifest.tools) {
    moduleSourceRefs.set(tool.sourceId, {
      exportName: tool.exportName,
      sourceKind: "module",
      logicalPath: tool.logicalPath,
      sourceId: tool.sourceId,
    });
  }

  for (const dynamicInstruction of manifest.dynamicInstructions) {
    moduleSourceRefs.set(dynamicInstruction.sourceId, {
      exportName: dynamicInstruction.exportName,
      sourceKind: "module",
      logicalPath: dynamicInstruction.logicalPath,
      sourceId: dynamicInstruction.sourceId,
    });
  }

  for (const dynamicSkill of manifest.dynamicSkills) {
    moduleSourceRefs.set(dynamicSkill.sourceId, {
      exportName: dynamicSkill.exportName,
      sourceKind: "module",
      logicalPath: dynamicSkill.logicalPath,
      sourceId: dynamicSkill.sourceId,
    });
  }

  for (const dynamicTool of manifest.dynamicTools) {
    moduleSourceRefs.set(dynamicTool.sourceId, {
      exportName: dynamicTool.exportName,
      sourceKind: "module",
      logicalPath: dynamicTool.logicalPath,
      sourceId: dynamicTool.sourceId,
    });
  }

  for (const remoteAgent of manifest.remoteAgents) {
    moduleSourceRefs.set(remoteAgent.sourceId, {
      exportName: remoteAgent.exportName,
      sourceKind: "module",
      logicalPath: remoteAgent.logicalPath,
      sourceId: remoteAgent.sourceId,
    });
  }

  for (const hook of manifest.hooks) {
    moduleSourceRefs.set(hook.sourceId, {
      exportName: hook.exportName,
      sourceKind: "module",
      logicalPath: hook.logicalPath,
      sourceId: hook.sourceId,
    });
  }

  for (const schedule of manifest.schedules) {
    // Only `run`-handler schedules need their source loaded at dispatch
    // time. Markdown schedules execute from `manifest.markdown`.
    if (schedule.sourceKind !== "module" || !schedule.hasRun) {
      continue;
    }
    moduleSourceRefs.set(schedule.sourceId, {
      sourceKind: "module",
      logicalPath: schedule.logicalPath,
      sourceId: schedule.sourceId,
    });
  }

  if (manifest.sandbox !== null) {
    moduleSourceRefs.set(manifest.sandbox.sourceId, {
      exportName: manifest.sandbox.exportName,
      sourceKind: "module",
      logicalPath: manifest.sandbox.logicalPath,
      sourceId: manifest.sandbox.sourceId,
    });
  }

  // Extension mount modules (root manifest only). Their top-level factory call
  // binds config, so they must be evaluated at module-map load.
  const extensionMounts = (manifest as { extensionMounts?: readonly CompiledExtensionMount[] })
    .extensionMounts;
  if (extensionMounts !== undefined) {
    for (const mount of extensionMounts) {
      moduleSourceRefs.set(mount.mountSourceId, {
        sourceKind: "module",
        logicalPath: mount.mountLogicalPath,
        sourceId: mount.mountSourceId,
      });
    }
  }

  // Authored system modules execute once at build time. The compiled markdown
  // is captured into the manifest, so there is no need to include them in the
  // runtime module map.

  return [...moduleSourceRefs.values()];
}

function createImportSpecifier(input: {
  fromDirectory: string;
  importSpecifierStyle: "absolute" | "relative";
  targetPath: string;
}): string {
  if (input.importSpecifierStyle === "absolute") {
    return normalizeEsmImportSpecifier(normalizeFilesystemPath(input.targetPath));
  }

  const relativeSpecifier = relativeFilesystemPath(input.fromDirectory, input.targetPath);

  if (relativeSpecifier.startsWith(".")) {
    return relativeSpecifier;
  }

  return `./${relativeSpecifier}`;
}

function renderModuleMap(scopes: readonly CollectedModuleNodeScope[]): string {
  return renderFrozenObject(
    [
      {
        key: "nodes",
        value: renderFrozenObject(
          scopes.map((scope) => ({
            key: scope.nodeId,
            value: renderFrozenObject(
              [
                {
                  key: "modules",
                  value: renderFrozenObject(
                    scope.modules.map((moduleImport) => ({
                      key: moduleImport.sourceId,
                      value: moduleImport.bindingName,
                    })),
                  ),
                },
              ],
              3,
            ),
          })),
        ),
      },
    ],
    0,
  );
}

function renderFrozenObject(
  entries: ReadonlyArray<{
    key: string;
    value: string;
  }>,
  depth: number = 1,
): string {
  if (entries.length === 0) {
    return "Object.freeze({})";
  }

  const indentation = "  ".repeat(depth);
  const nestedIndentation = "  ".repeat(depth + 1);

  return [
    "Object.freeze({",
    entries
      .map((entry) => {
        return `${nestedIndentation}${JSON.stringify(entry.key)}: ${entry.value.replaceAll("\n", `\n${nestedIndentation}`)}`;
      })
      .join(",\n"),
    `${indentation}})`,
  ].join("\n");
}

function dirnameFilesystemPath(path: string): string {
  const parsed = splitFilesystemPath(path);

  if (parsed.segments.length === 0) {
    return parsed.root.length === 0 ? "." : parsed.root;
  }

  return createFilesystemPath(parsed.root, parsed.segments.slice(0, -1));
}

function relativeFilesystemPath(fromDirectory: string, targetPath: string): string {
  const from = splitFilesystemPath(fromDirectory);
  const target = splitFilesystemPath(targetPath);

  if (from.root !== target.root) {
    return normalizeFilesystemPath(targetPath);
  }

  let sharedIndex = 0;

  while (
    sharedIndex < from.segments.length &&
    sharedIndex < target.segments.length &&
    from.segments[sharedIndex] === target.segments[sharedIndex]
  ) {
    sharedIndex += 1;
  }

  const relativeSegments = [
    ...Array.from({ length: from.segments.length - sharedIndex }, () => ".."),
    ...target.segments.slice(sharedIndex),
  ];

  return relativeSegments.length === 0 ? "." : relativeSegments.join("/");
}

function normalizeFilesystemPath(path: string): string {
  const parsed = splitFilesystemPath(path);
  return createFilesystemPath(parsed.root, parsed.segments);
}

function splitFilesystemPath(path: string): {
  readonly root: string;
  readonly segments: string[];
} {
  const normalized = path.replaceAll("\\", "/");
  let root = "";
  let remainder = normalized;

  const windowsDriveMatch = normalized.match(/^[A-Za-z]:/);

  if (windowsDriveMatch !== null) {
    root = windowsDriveMatch[0];
    remainder = normalized.slice(root.length);

    if (remainder.startsWith("/")) {
      root = `${root}/`;
      remainder = remainder.slice(1);
    }
  } else if (normalized.startsWith("/")) {
    root = "/";
    remainder = normalized.slice(1);
  }

  const segments: string[] = [];

  for (const segment of remainder.split("/")) {
    if (segment.length === 0 || segment === ".") {
      continue;
    }

    if (segment === "..") {
      if (segments.length > 0 && segments[segments.length - 1] !== "..") {
        segments.pop();
        continue;
      }

      if (root.length === 0) {
        segments.push(segment);
      }

      continue;
    }

    segments.push(segment);
  }

  return {
    root,
    segments,
  };
}

function createFilesystemPath(root: string, segments: readonly string[]): string {
  if (root === "/") {
    return segments.length === 0 ? "/" : `/${segments.join("/")}`;
  }

  if (root.endsWith("/")) {
    return segments.length === 0 ? root : `${root}${segments.join("/")}`;
  }

  if (root.length > 0) {
    return segments.length === 0 ? root : `${root}/${segments.join("/")}`;
  }

  return segments.length === 0 ? "." : segments.join("/");
}
