import { z } from "#compiled/zod/index.js";
import type {
  CompiledAgentManifest,
  CompiledAgentNodeManifest,
  CompiledAgentResources,
} from "#compiler/manifest.js";
import { ROOT_COMPILED_AGENT_NODE_ID } from "#compiler/manifest.js";
import {
  type AgentSourceRegistry,
  type CompiledModuleBinding,
  type ProgrammaticModuleNamespace,
} from "#compiler/source-graph.js";
import { createCompiledBindingNamespaceLoader } from "#compiler/load-binding-namespace.js";
import { normalizeEsmImportSpecifier } from "#internal/application/import-specifier.js";

export { resolveCompiledModuleExtensionScopeNamespace } from "#compiler/load-binding-namespace.js";

export type CompiledModuleNodeScope = z.infer<typeof compiledModuleNodeScopeSchema>;
export type CompiledModuleMap = z.infer<typeof compiledModuleMapSchema>;

const compiledModuleNodeScopeSchema = z
  .object({ modules: z.record(z.string(), z.object({}).passthrough()) })
  .strict();

export const compiledModuleMapSchema = z
  .object({ nodes: z.record(z.string(), compiledModuleNodeScopeSchema) })
  .strict();

export interface CreateCompiledModuleMapSourceInput {
  importSpecifierStyle?: "absolute" | "relative";
  manifest: CompiledAgentManifest;
  moduleMapPath: string;
  programmaticLoaderImportSpecifier?: string;
}

interface BoundModule {
  readonly binding: CompiledModuleBinding;
  readonly sourceId: string;
}

interface BoundNodeScope {
  readonly modules: readonly BoundModule[];
  readonly nodeId: string;
}

interface RenderedModule {
  readonly bindingName: string;
  readonly initializer?: string;
  readonly importSpecifier?: string;
  readonly sourceId: string;
}

interface RenderedNodeScope {
  readonly modules: readonly RenderedModule[];
  readonly nodeId: string;
}

/** Generates the authoritative module-map artifact from required bindings. */
export function createCompiledModuleMapSource(input: CreateCompiledModuleMapSourceInput): string {
  const moduleMapDirectory = dirnameFilesystemPath(input.moduleMapPath);
  const importSpecifierStyle = input.importSpecifierStyle ?? "relative";
  let index = 0;
  let usesProgrammaticLoader = false;
  const scopes: RenderedNodeScope[] = collectBoundNodeScopes(input.manifest).map((scope) => {
    const bindingNames = new Map(
      scope.modules.map((module) => [module.sourceId, `module_${index++}`] as const),
    );
    return {
      modules: scope.modules.map(({ binding, sourceId }) => {
        const bindingName = bindingNames.get(sourceId)!;
        if (binding.backing.kind === "filesystem") {
          return {
            bindingName,
            importSpecifier: createImportSpecifier({
              fromDirectory: moduleMapDirectory,
              importSpecifierStyle,
              targetPath: binding.backing.sourcePath,
            }),
            initializer: `memoizeModuleNamespaceFactories(imported_${bindingName})`,
            sourceId,
          };
        }
        usesProgrammaticLoader = true;
        return {
          bindingName,
          initializer: `await loadProgrammaticModule(${JSON.stringify(binding.backing)}, ${renderProgrammaticDependencies(binding.backing.dependencies, bindingNames)})`,
          sourceId,
        };
      }),
      nodeId: scope.nodeId,
    };
  });
  const modules = scopes.flatMap((scope) => scope.modules);
  const imports = modules.flatMap((module) =>
    module.importSpecifier === undefined
      ? []
      : [
          `import * as imported_${module.bindingName} from ${JSON.stringify(module.importSpecifier)};`,
        ],
  );
  const initializers = modules.flatMap((module) =>
    module.initializer === undefined
      ? []
      : [`const ${module.bindingName} = ${module.initializer};`],
  );

  return [
    "// Generated by eve. Do not edit by hand.",
    ...(usesProgrammaticLoader || imports.length > 0
      ? [
          `import { loadFrameworkProgrammaticModule as loadProgrammaticModule, memoizeModuleNamespaceFactories } from ${JSON.stringify(normalizeEsmImportSpecifier(input.programmaticLoaderImportSpecifier ?? "eve/internal/programmatic-source-loader"))};`,
        ]
      : []),
    ...imports,
    ...(usesProgrammaticLoader || imports.length > 0 ? [""] : []),
    ...initializers,
    ...(initializers.length > 0 ? [""] : []),
    `export const moduleMap = ${renderModuleMap(scopes)};`,
    "",
    "export default moduleMap;",
    "",
  ].join("\n");
}

/** Loads the same binding set used by generated maps without fabricating descriptors. */
export async function createProgrammaticCompiledModuleMap(
  manifest: CompiledAgentManifest,
  registries: readonly AgentSourceRegistry[],
): Promise<CompiledModuleMap> {
  const nodes: CompiledModuleMap["nodes"] = {};
  for (const scope of collectBoundNodeScopes(manifest)) {
    const modules: Record<string, ProgrammaticModuleNamespace> = {};
    const bindings = Object.fromEntries(
      scope.modules.map(({ binding, sourceId }) => [sourceId, binding]),
    );
    const loadNamespace = createCompiledBindingNamespaceLoader({ bindings, registries });
    for (const { sourceId } of scope.modules) {
      modules[sourceId] = await loadNamespace(sourceId);
    }
    nodes[scope.nodeId] = { modules };
  }
  return { nodes };
}

/** Returns one compiled node's finalized runtime entries, including remote config modules. */
export function collectRuntimeModuleBindingsForManifest(
  manifest: CompiledAgentNodeManifest | CompiledAgentResources,
): readonly BoundModule[] {
  const modules = new Map<string, CompiledModuleBinding>(
    Object.entries(manifest.bindings).filter(([, binding]) => binding.usage.runtimeEntry),
  );
  for (const remote of manifest.remoteAgents) {
    if (!remote.binding.usage.runtimeEntry) continue;
    if (modules.has(remote.sourceId)) {
      throw new Error(`Remote agent binding "${remote.sourceId}" collides with a node binding.`);
    }
    modules.set(remote.sourceId, remote.binding);
  }
  return orderBoundModules(
    [...modules]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([sourceId, binding]) => ({ binding, sourceId })),
  );
}

function orderBoundModules(modules: readonly BoundModule[]): readonly BoundModule[] {
  const bySourceId = new Map(modules.map((module) => [module.sourceId, module]));
  const ordered: BoundModule[] = [];
  const visiting = new Set<string>();
  const visited = new Set<string>();
  const visit = (module: BoundModule): void => {
    if (visited.has(module.sourceId)) return;
    if (visiting.has(module.sourceId)) {
      throw new Error(`Compiled module dependency cycle includes "${module.sourceId}".`);
    }
    visiting.add(module.sourceId);
    if (module.binding.backing.kind === "programmatic") {
      for (const dependencySourceId of Object.values(module.binding.backing.dependencies ?? {})) {
        const dependency = bySourceId.get(dependencySourceId);
        if (dependency === undefined) {
          throw new Error(
            `Programmatic binding "${module.sourceId}" depends on missing binding "${dependencySourceId}".`,
          );
        }
        visit(dependency);
      }
    }
    visiting.delete(module.sourceId);
    visited.add(module.sourceId);
    ordered.push(module);
  };
  for (const module of modules) visit(module);
  return ordered;
}

function renderProgrammaticDependencies(
  dependencies: Readonly<Record<string, string>> | undefined,
  bindingNames: ReadonlyMap<string, string>,
): string {
  const entries = Object.entries(dependencies ?? {});
  if (entries.length === 0) return "Object.freeze({})";
  return `Object.freeze({ ${entries
    .map(([alias, sourceId]) => `${JSON.stringify(alias)}: ${bindingNames.get(sourceId)!}`)
    .join(", ")} })`;
}

function collectBoundNodeScopes(manifest: CompiledAgentManifest): readonly BoundNodeScope[] {
  return [
    {
      modules: collectRuntimeModuleBindingsForManifest(manifest),
      nodeId: ROOT_COMPILED_AGENT_NODE_ID,
    },
    ...[...manifest.subagents]
      .sort((left, right) => left.nodeId.localeCompare(right.nodeId))
      .map((subagent) => ({
        modules: collectRuntimeModuleBindingsForManifest(subagent.agent),
        nodeId: subagent.nodeId,
      })),
  ];
}

function renderModuleMap(scopes: readonly RenderedNodeScope[]): string {
  return renderFrozenObject(
    [
      {
        key: "nodes",
        value: renderFrozenObject(
          scopes.map((scope) => ({
            key: scope.nodeId,
            value: renderFrozenObject(
              [
                {
                  key: "modules",
                  value: renderFrozenObject(
                    scope.modules.map((module) => ({
                      key: module.sourceId,
                      value: module.bindingName,
                    })),
                  ),
                },
              ],
              3,
            ),
          })),
        ),
      },
    ],
    0,
  );
}

function renderFrozenObject(
  entries: ReadonlyArray<{ readonly key: string; readonly value: string }>,
  depth: number = 1,
): string {
  if (entries.length === 0) return "Object.freeze({})";
  const indentation = "  ".repeat(depth);
  const nestedIndentation = "  ".repeat(depth + 1);
  return [
    "Object.freeze({",
    entries
      .map(
        (entry) =>
          `${nestedIndentation}${JSON.stringify(entry.key)}: ${entry.value.replaceAll("\n", `\n${nestedIndentation}`)}`,
      )
      .join(",\n"),
    `${indentation}})`,
  ].join("\n");
}

function createImportSpecifier(input: {
  readonly fromDirectory: string;
  readonly importSpecifierStyle: "absolute" | "relative";
  readonly targetPath: string;
}): string {
  if (input.importSpecifierStyle === "absolute") {
    return normalizeEsmImportSpecifier(normalizeFilesystemPath(input.targetPath));
  }
  const relativeSpecifier = relativeFilesystemPath(input.fromDirectory, input.targetPath);
  return relativeSpecifier.startsWith(".") ? relativeSpecifier : `./${relativeSpecifier}`;
}

function dirnameFilesystemPath(path: string): string {
  const parsed = splitFilesystemPath(path);
  if (parsed.segments.length === 0) return parsed.root.length === 0 ? "." : parsed.root;
  return createFilesystemPath(parsed.root, parsed.segments.slice(0, -1));
}

function relativeFilesystemPath(fromDirectory: string, targetPath: string): string {
  const from = splitFilesystemPath(fromDirectory);
  const target = splitFilesystemPath(targetPath);
  if (from.root !== target.root) return normalizeFilesystemPath(targetPath);
  let sharedIndex = 0;
  while (
    sharedIndex < from.segments.length &&
    sharedIndex < target.segments.length &&
    from.segments[sharedIndex] === target.segments[sharedIndex]
  ) {
    sharedIndex += 1;
  }
  return (
    [
      ...Array.from({ length: from.segments.length - sharedIndex }, () => ".."),
      ...target.segments.slice(sharedIndex),
    ].join("/") || "."
  );
}

function normalizeFilesystemPath(path: string): string {
  const parsed = splitFilesystemPath(path);
  return createFilesystemPath(parsed.root, parsed.segments);
}

function splitFilesystemPath(path: string): { readonly root: string; readonly segments: string[] } {
  const normalized = path.replaceAll("\\", "/");
  let root = "";
  let remainder = normalized;
  const windowsDrive = normalized.match(/^[A-Za-z]:/);
  if (windowsDrive !== null) {
    root = windowsDrive[0];
    remainder = normalized.slice(root.length);
    if (remainder.startsWith("/")) {
      root += "/";
      remainder = remainder.slice(1);
    }
  } else if (normalized.startsWith("/")) {
    root = "/";
    remainder = normalized.slice(1);
  }
  const segments: string[] = [];
  for (const segment of remainder.split("/")) {
    if (segment.length === 0 || segment === ".") continue;
    if (segment === "..") {
      if (segments.length > 0 && segments.at(-1) !== "..") segments.pop();
      else if (root.length === 0) segments.push(segment);
    } else segments.push(segment);
  }
  return { root, segments };
}

function createFilesystemPath(root: string, segments: readonly string[]): string {
  if (root === "/") return segments.length === 0 ? "/" : `/${segments.join("/")}`;
  if (root.endsWith("/")) return segments.length === 0 ? root : `${root}${segments.join("/")}`;
  if (root.length > 0) return segments.length === 0 ? root : `${root}/${segments.join("/")}`;
  return segments.length === 0 ? "." : segments.join("/");
}
